### ISSUE TITLE
Document how to use as a Python library

### ISSUE THREAD

**Issue by choldgraf** [ExecutableBookProject/jupyter-cache#15]
Currently the README focuses on the CLI use-case for Jupyter-Cache. I think that we'll probably want to use the Python API when using it as a part of a build system. We should document this part of the user-facing API.

**Comment by mmcky** [comment]
@choldgraf -- @chrisjsewell and I had a discussion on this topic yesterday. I will meet up with @aakash today to discuss ways we can link `myst-parser` and `myst-nb` to get the outputs added to notebooks. We will look at the python api rather than the cli -- but @chrisjsewell suggested looking at the CLI to understand how the python api is put together.
